"""Added highlighted column to ContactMessage

Revision ID: 884947d6a114
Revises: 
Create Date: 2025-01-30 01:54:52.145096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '884947d6a114'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('highlighted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_message', schema=None) as batch_op:
        batch_op.drop_column('highlighted')

    # ### end Alembic commands ###
